---
- name: Install Docker engine
  hosts: localhost
  become: true
  tasks:
  - name: install dependencies
    apt:
      name: 
       - ca-certificates 
       - curl 
       - gnupg 
       - lsb-release
      state: present
      update_cache: true
    become: true

  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository to apt
    apt_repository:
      filename: docker 
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: install docker engine
    apt:
      name: 
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
      state: present
      update_cache: true
    become: true
    
    - name: Install docker-compose
      remote_user: ansible_ubuntu_demo
      get_url:
      url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

#     collections:
#   - name: community.docker

#   - name: test docker
#     command: docker info
#     become: true

# - name: Install SonarQube
#   hosts: sonarqube
#   become: true
#   vars:
#     # java
#     java_major_version: 11.0.16
#     transport: repositories
#     # postgresql
#     postgresql_users:
#       - name: sonar
#         pass: sonar
#     postgresql_databases:
#       - name: sonar
#         owner: sonar
#     # ssl-certs
#     ssl_certs_path_owner: nginx
#     ssl_certs_path_group: nginx
#     ssl_certs_common_name: sonarqube.example.com
    # sonarqube
    sonar_version: latest
    sonar_check_url: 'http://{{ ansible_fqdn }}:9000'
    sonar_proxy_server_name: sonarqube.example.com
    sonar_install_optional_plugins: true
    sonar_optional_plugins: 
      - 'https://github.com/adnovum/sonar-build-breaker/releases/download/{{ build_breaker_epversion }}'
    sonar_default_excluded_plugins:
      - '{{ sonar_plugins_path }}/sonar-csharp-plugin-8.15.0.24505.jar'
    sonar_web_password: your_new_secure_password
    change_password: true
    sonar_web_old_password: admin
    sonar_migrate_db: true  # set to true if updating SonarQube to new version 
    sonar_set_jenkins_webhook: true
    sonar_jenkins_webhook_url: https://jenkins.example.com/sonarqube-webhook/
    sonar_restore_profiles: true
    sonar_profile_list:
      - files/example_profile.xml